name: Static Code Checks
run-name: code_checks
on: [push]
jobs:
  run-static_code_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: tox -e type,lint_check